### ISSUE TITLE
 Not all objects were uploaded to SAP after YABAPGIT_STANDALONE Sample Code App POF upload

### ISSUE THREAD

**Issue by ACFreitasC2** [SAP-samples/logistics-business-network-integration#5]
Hi SAP GitHUb LBN-GTT Team,

Can you help me with the following issue related 

After downloading the ABAP Code from GitHub in the new program created YABAPGIT_STANDALONE, 
we noticed in the execution of ERP transaction SE80 that not all objects were uploaded to SAP.

This ended up impacting the creation of Purchase Orders – preventing creation.

We were unable to do the "online download" described in Track POF App Extractor Creation
Guide, so we did the "Offline" process
(steps described in page 56)

Not all objects were loaded in SAP SE80

Any suggestion?
Appreciate yourhelp!
Thanks!
Alexandre Freitas

**Comment by ACFreitasC2** [comment]
Hi! 
Any comments?
Thanks!
Alexandre

**Comment by qopod** [comment]
Hi, 
After investigating from our colleagues, we have following finding:
Root cause:
3rd party tool-AbapGit (This tool is not maintained and owned by SAP) has some issues cannot import POF code(Our product) into customer’s S4 system.

Action plan:
will tracking this issue in ticket 99970/2022(Missing objects in SAP after YABAPGIT_STANDALONE).

if you have more issue, please contact us, thanks a lot.


William.
